/* Keep Sharp question bank.
 *
 * Add a question by copying an object into QUESTIONS. The game logic in
 * app.js does not need to change. topic must be "algebra", "geometry",
 * or "calculus" (or a new id you also add to TOPICS in app.js).
 *
 * Fields:
 *   id             unique string
 *   topic          "algebra" | "geometry" | "calculus"
 *   difficulty     "easy" | "medium" | "hard"
 *   prompt         sentence with \( inline \) or \[ display \] KaTeX
 *   choices        exactly four strings, or five for a GMAT-style question
 *   correct        index into choices before any shuffle
 *   shuffle        optional. Omit it to shuffle. Data sufficiency sets false
 *                  so choices A–E keep their standard meanings.
 *   displayAnswer  official answer shown after a pick, usually choices[correct]
 *   explanation    1–3 sentences on why that answer is right, with the key step.
 *                  Plain text, with optional \( inline \) KaTeX. Omit it only if
 *                  you have nothing accurate to say; the game then shows nothing.
 *   hint           one starter tip that does not state the final answer
 *   formula        key formula in KaTeX, usually \[ display \]
 *   lesson         2–4 plain sentences. No HTML.
 *   learnUrl       stable topic page (Khan Academy, Paul's notes, Math is Fun)
 *   learnLabel     text for that link
 *
 * Wrong choices should be common slips (a missed sign, a forgotten factor,
 * the nearby formula), not jokes. The game shuffles choices on each show
 * unless a question sets shuffle to false.
 */
var QUESTIONS = [
  {
    id: "alg-linear",
    topic: "algebra",
    difficulty: "easy",
    prompt: "Solve for \\(x\\): \\(2x + 6 = 14\\).",
    choices: ["\\(x = 4\\)", "\\(x = 8\\)", "\\(x = 10\\)", "\\(x = 7\\)"],
    correct: 0,
    displayAnswer: "\\(x = 4\\)",
    explanation: "Subtract 6 from both sides: \\(2x = 8\\). Divide by 2 to get \\(x = 4\\).",
    hint: "Undo the addition first, then undo the multiplication.",
    formula: "\\[ax + b = c \\quad\\Rightarrow\\quad x = \\frac{c - b}{a}\\]",
    lesson: "A linear equation has the variable only to the first power. To solve it, undo whatever is done to the variable, working from the outside in, and do the same operation to both sides. Check by substituting your value back into the original equation.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-both-sides",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Solve for \\(x\\): \\(5x - 3 = 2x + 9\\).",
    choices: ["\\(x = 4\\)", "\\(x = 2\\)", "\\(x = 6\\)", "\\(x = 12\\)"],
    correct: 0,
    displayAnswer: "\\(x = 4\\)",
    explanation: "Subtract \\(2x\\) from both sides: \\(3x - 3 = 9\\). Add 3 and divide by 3 to get \\(x = 4\\).",
    hint: "Collect the x terms on one side and the numbers on the other, then divide.",
    formula: "\\[ax + b = cx + d \\quad\\Rightarrow\\quad x = \\frac{d - b}{a - c}\\]",
    lesson: "When the variable appears on both sides, gather the variable terms on one side and the constants on the other. Add or subtract the same amount on both sides before you divide. The result is still one number that makes the two sides equal.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-slope",
    topic: "algebra",
    difficulty: "easy",
    prompt: "What is the slope of the line through \\((1, 2)\\) and \\((4, 8)\\)?",
    choices: ["\\(2\\)", "\\(\\dfrac{1}{2}\\)", "\\(-2\\)", "\\(6\\)"],
    correct: 0,
    displayAnswer: "\\(2\\)",
    explanation: "Change in \\(y\\) over change in \\(x\\) is \\((8-2)/(4-1) = 6/3\\). That simplifies to 2.",
    hint: "Divide the change in y by the change in x, and subtract the coordinates in the same order.",
    formula: "\\[m = \\frac{y_2 - y_1}{x_2 - x_1}\\]",
    lesson: "Slope measures how much y changes for each step in x, often called rise over run. Subtract the y-coordinates and divide by the difference of the x-coordinates, using the same point order in both subtractions. A positive slope climbs as x increases, and a negative slope falls.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/Lines.aspx",
    learnLabel: "Paul's Online Math Notes: Lines"
  },
  {
    id: "alg-line-value",
    topic: "algebra",
    difficulty: "easy",
    prompt: "A line has equation \\(y = 2x + 3\\). What is \\(y\\) when \\(x = 4\\)?",
    choices: ["\\(11\\)", "\\(8\\)", "\\(14\\)", "\\(7\\)"],
    correct: 0,
    displayAnswer: "\\(11\\)",
    explanation: "Substitute \\(x = 4\\): \\(y = 2(4) + 3 = 11\\).",
    hint: "Substitute the given x. The equation is already solved for y.",
    formula: "\\[y = mx + b\\]",
    lesson: "Slope-intercept form names the slope as m and the y-intercept as b. To find y at a given x, substitute that x and simplify. The intercept is the y-value when x is zero, and it is already sitting in the equation.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/Lines.aspx",
    learnLabel: "Paul's Online Math Notes: Lines"
  },
  {
    id: "alg-factor",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Factor \\(x^2 + 5x + 6\\).",
    choices: ["\\((x + 2)(x + 3)\\)", "\\((x + 1)(x + 6)\\)", "\\((x - 2)(x - 3)\\)", "\\((x + 2)(x + 4)\\)"],
    correct: 0,
    displayAnswer: "\\((x + 2)(x + 3)\\)",
    explanation: "The numbers 2 and 3 multiply to 6 and add to 5. That gives \\((x+2)(x+3)\\).",
    hint: "Look for two binomials whose constants multiply to the last term and add to the middle coefficient.",
    formula: "\\[x^2 + (p + q)x + pq = (x + p)(x + q)\\]",
    lesson: "A quadratic factors into two binomials when you can find a pair of numbers that multiply to the constant term and add to the middle coefficient. Those two numbers become the constants in the binomials. Multiplying the binomials back out should recover the original quadratic.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/Factoring.aspx",
    learnLabel: "Paul's Online Math Notes: Factoring"
  },
  {
    id: "alg-roots",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Solve \\(x^2 - 5x + 6 = 0\\).",
    choices: ["\\(x = 2\\) or \\(x = 3\\)", "\\(x = -2\\) or \\(x = -3\\)", "\\(x = 1\\) or \\(x = 6\\)", "\\(x = -1\\) or \\(x = 6\\)"],
    correct: 0,
    displayAnswer: "\\(x = 2\\) or \\(x = 3\\)",
    explanation: "Factor the left side as \\((x-2)(x-3) = 0\\). Each factor gives a solution: \\(x = 2\\) or \\(x = 3\\).",
    hint: "Factor the left side, then set each factor equal to zero.",
    formula: "\\[x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}\\]",
    lesson: "If a product of factors is zero, then at least one factor is zero. Factor the quadratic, set each binomial equal to zero, and solve those simpler equations. The quadratic formula is the backup when factoring is not obvious, and both roots count as solutions.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "alg-discriminant",
    topic: "algebra",
    difficulty: "medium",
    prompt: "For \\(x^2 - 4x - 5 = 0\\), what is the discriminant \\(b^2 - 4ac\\)?",
    choices: ["\\(36\\)", "\\(-4\\)", "\\(16\\)", "\\(20\\)"],
    correct: 0,
    displayAnswer: "\\(36\\)",
    explanation: "Here \\(a = 1\\), \\(b = -4\\), and \\(c = -5\\). Then \\(b^2 - 4ac = 16 - 4(1)(-5) = 36\\).",
    hint: "Identify a, b, and c with their signs, then compute b squared minus 4ac. You do not need the roots.",
    formula: "\\[\\text{discriminant} = b^2 - 4ac\\]",
    lesson: "The quadratic formula uses a, b, and c from a quadratic set equal to zero. The discriminant is the expression under the square root, and its sign tells you how many real roots to expect. Keep the signs of b and c when you square and multiply.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "alg-system",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Solve the system \\(x + y = 10\\) and \\(x - y = 2\\).",
    choices: ["\\(x = 6,\\; y = 4\\)", "\\(x = 4,\\; y = 6\\)", "\\(x = 8,\\; y = 2\\)", "\\(x = 10,\\; y = 2\\)"],
    correct: 0,
    displayAnswer: "\\(x = 6,\\; y = 4\\)",
    explanation: "Adding the equations gives \\(2x = 12\\), so \\(x = 6\\). Then \\(6 + y = 10\\), so \\(y = 4\\).",
    hint: "Add the equations to eliminate one variable, then substitute to find the other.",
    formula: "\\[\\begin{aligned} x + y &= c \\\\ x - y &= d \\end{aligned}\\]",
    lesson: "A system asks for the pair of values that makes every equation true at the same time. Adding the equations can eliminate one variable when its coefficients are opposites. Once you know one variable, substitute it into either equation to find the other.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx",
    learnLabel: "Paul's Online Math Notes: Systems of Equations"
  },
  {
    id: "alg-exponents",
    topic: "algebra",
    difficulty: "easy",
    prompt: "Evaluate \\(2^3 \\cdot 2^4\\).",
    choices: ["\\(128\\)", "\\(64\\)", "\\(24\\)", "\\(4096\\)"],
    correct: 0,
    displayAnswer: "\\(128\\)",
    explanation: "The bases match, so add the exponents: \\(2^{3+4} = 2^7\\). Then \\(2^7 = 128\\).",
    hint: "Add the exponents because the bases match, then evaluate that power.",
    formula: "\\[a^m \\cdot a^n = a^{m+n}\\]",
    lesson: "When you multiply powers with the same base, keep the base and add the exponents. You can then evaluate the single power by multiplying the base by itself that many times. Different bases do not combine this way until you rewrite them with a common base.",
    learnUrl: "https://www.mathsisfun.com/algebra/exponent-laws.html",
    learnLabel: "Math is Fun: Exponent Laws"
  },
  {
    id: "alg-log",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Evaluate \\(\\log_2 32\\).",
    choices: ["\\(5\\)", "\\(4\\)", "\\(6\\)", "\\(16\\)"],
    correct: 0,
    displayAnswer: "\\(5\\)",
    explanation: "The log asks which power of 2 equals 32. Since \\(2^5 = 32\\), the value is 5.",
    hint: "Rewrite the question as 2 raised to what power equals 32.",
    formula: "\\[\\log_b a = c \\quad\\Leftrightarrow\\quad b^c = a\\]",
    lesson: "A logarithm asks for an exponent. The log base 2 of a number is the power you raise 2 to in order to get that number. Listing powers of 2 is a reliable way to find small integer logs.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/LogFunctions.aspx",
    learnLabel: "Paul's Online Math Notes: Logarithm Functions"
  },
  {
    id: "geo-pythag",
    topic: "geometry",
    difficulty: "easy",
    prompt: "A right triangle has legs of length \\(3\\) and \\(4\\). How long is the hypotenuse?",
    choices: ["\\(5\\)", "\\(7\\)", "\\(25\\)", "\\(\\sqrt{7}\\)"],
    correct: 0,
    displayAnswer: "\\(5\\)",
    explanation: "Add the squares of the legs: \\(3^2 + 4^2 = 25\\). The hypotenuse is \\(\\sqrt{25} = 5\\).",
    hint: "Square each leg, add the squares, and take the square root.",
    formula: "\\[a^2 + b^2 = c^2\\]",
    lesson: "The Pythagorean theorem applies to right triangles only. The two legs are the sides that meet at the right angle, and the hypotenuse is the side opposite that angle. Square the legs, add those squares, and the hypotenuse is the square root of the sum.",
    learnUrl: "https://www.mathsisfun.com/pythagoras.html",
    learnLabel: "Math is Fun: Pythagoras' Theorem"
  },
  {
    id: "geo-leg",
    topic: "geometry",
    difficulty: "medium",
    prompt: "A right triangle has hypotenuse \\(13\\) and one leg \\(5\\). How long is the other leg?",
    choices: ["\\(12\\)", "\\(8\\)", "\\(\\sqrt{194}\\)", "\\(144\\)"],
    correct: 0,
    displayAnswer: "\\(12\\)",
    explanation: "The missing leg satisfies \\(b^2 = 13^2 - 5^2 = 144\\). So \\(b = \\sqrt{144} = 12\\).",
    hint: "Subtract the known leg's square from the hypotenuse's square, then take the square root.",
    formula: "\\[b = \\sqrt{c^2 - a^2}\\]",
    lesson: "The Pythagorean theorem still applies when the hypotenuse is the known side. Square the hypotenuse and subtract the square of the known leg. The other leg is the square root of what remains, and a length is positive.",
    learnUrl: "https://www.mathsisfun.com/pythagoras.html",
    learnLabel: "Math is Fun: Pythagoras' Theorem"
  },
  {
    id: "geo-rectangle",
    topic: "geometry",
    difficulty: "easy",
    prompt: "A rectangle is \\(7\\) units long and \\(5\\) units wide. What is its area?",
    choices: ["\\(35\\)", "\\(24\\)", "\\(12\\)", "\\(70\\)"],
    correct: 0,
    displayAnswer: "\\(35\\)",
    explanation: "Multiply the side lengths: \\(7 \\times 5 = 35\\).",
    hint: "Multiply the two side lengths.",
    formula: "\\[A = \\ell w\\]",
    lesson: "The area of a rectangle is the product of its length and width. Units of area are squared, such as square centimeters, even when a problem only asks for the number. If the sides are perpendicular, you do not need a diagonal or an angle.",
    learnUrl: "https://www.mathsisfun.com/geometry/rectangle.html",
    learnLabel: "Math is Fun: Rectangles"
  },
  {
    id: "geo-triangle-area",
    topic: "geometry",
    difficulty: "easy",
    prompt: "A triangle has base \\(10\\) and height \\(6\\). What is its area?",
    choices: ["\\(30\\)", "\\(60\\)", "\\(16\\)", "\\(15\\)"],
    correct: 0,
    displayAnswer: "\\(30\\)",
    explanation: "Take half of base times height: \\(\\frac{1}{2} \\times 10 \\times 6 = 30\\).",
    hint: "Take half of base times height. Use the perpendicular height.",
    formula: "\\[A = \\frac{1}{2}bh\\]",
    lesson: "The area of a triangle is half the product of a base and the height perpendicular to that base. The height has to meet the base at a right angle, even if that meeting point is outside the triangle. Skipping the one-half gives the area of a parallelogram instead.",
    learnUrl: "https://www.mathsisfun.com/area.html",
    learnLabel: "Math is Fun: Area"
  },
  {
    id: "geo-circle-area",
    topic: "geometry",
    difficulty: "medium",
    prompt: "A circle has radius \\(3\\). What is its area?",
    choices: ["\\(9\\pi\\)", "\\(6\\pi\\)", "\\(3\\pi\\)", "\\(36\\pi\\)"],
    correct: 0,
    displayAnswer: "\\(9\\pi\\)",
    explanation: "Square the radius, then multiply by \\(\\pi\\): \\(3^2\\pi = 9\\pi\\).",
    hint: "Start from π times the radius squared.",
    formula: "\\[A = \\pi r^2\\]",
    lesson: "The area of a circle is π times the radius squared. Square the radius first, then multiply by π, rather than squaring the whole product. Unless a problem asks for a decimal, leave π in the answer so the value stays exact.",
    learnUrl: "https://www.mathsisfun.com/geometry/circle-area.html",
    learnLabel: "Math is Fun: Area of a Circle"
  },
  {
    id: "geo-circumference",
    topic: "geometry",
    difficulty: "medium",
    prompt: "A circle has radius \\(5\\). What is its circumference?",
    choices: ["\\(10\\pi\\)", "\\(25\\pi\\)", "\\(5\\pi\\)", "\\(20\\pi\\)"],
    correct: 0,
    displayAnswer: "\\(10\\pi\\)",
    explanation: "Circumference is \\(2\\pi r\\). With \\(r = 5\\), that is \\(2\\pi \\times 5 = 10\\pi\\).",
    hint: "The radius goes into the circumference formula.",
    formula: "\\[C = 2\\pi r\\]",
    lesson: "The circumference is the distance around a circle, equal to 2π times the radius, or π times the diameter. The radius is half the diameter, so check which one the problem gives you. Leaving π in the answer keeps the measurement exact.",
    learnUrl: "https://www.mathsisfun.com/geometry/circle.html",
    learnLabel: "Math is Fun: Circles"
  },
  {
    id: "geo-prism",
    topic: "geometry",
    difficulty: "easy",
    prompt: "A rectangular prism measures \\(2\\) by \\(3\\) by \\(4\\). What is its volume?",
    choices: ["\\(24\\)", "\\(52\\)", "\\(9\\)", "\\(48\\)"],
    correct: 0,
    displayAnswer: "\\(24\\)",
    explanation: "Multiply the three edge lengths: \\(2 \\times 3 \\times 4 = 24\\).",
    hint: "Multiply the three edge lengths that meet at a corner.",
    formula: "\\[V = \\ell w h\\]",
    lesson: "The volume of a rectangular prism is length times width times height. Any edge can be called the height as long as you use the three dimensions that meet at a corner. Volume is measured in cubic units.",
    learnUrl: "https://www.mathsisfun.com/geometry/cuboids-rectangular-prisms.html",
    learnLabel: "Math is Fun: Rectangular Prisms"
  },
  {
    id: "geo-cylinder",
    topic: "geometry",
    difficulty: "medium",
    prompt: "A cylinder has radius \\(2\\) and height \\(5\\). What is its volume?",
    choices: ["\\(20\\pi\\)", "\\(10\\pi\\)", "\\(40\\pi\\)", "\\(28\\pi\\)"],
    correct: 0,
    displayAnswer: "\\(20\\pi\\)",
    explanation: "The base area is \\(\\pi r^2 = 4\\pi\\). Multiply by the height: \\(4\\pi \\times 5 = 20\\pi\\).",
    hint: "Find the area of the circular base, then multiply by the height.",
    formula: "\\[V = \\pi r^2 h\\]",
    lesson: "A cylinder's volume is the area of its circular base times its height. The base area is π times the radius squared, so the volume multiplies that area by the height. Keep π in an exact answer, and do not confuse this with the surface area, which also counts the side wall.",
    learnUrl: "https://www.mathsisfun.com/geometry/cylinder.html",
    learnLabel: "Math is Fun: Cylinders"
  },
  {
    id: "geo-similar",
    topic: "geometry",
    difficulty: "medium",
    prompt: "A triangle with sides \\(3\\), \\(4\\), and \\(5\\) is enlarged by a scale factor of \\(2\\). What is the longest side of the new triangle?",
    choices: ["\\(10\\)", "\\(5\\)", "\\(7\\)", "\\(20\\)"],
    correct: 0,
    displayAnswer: "\\(10\\)",
    explanation: "The longest original side is 5, and lengths scale by 2. The new longest side is \\(5 \\times 2 = 10\\).",
    hint: "The longest side of the new triangle corresponds to the longest side of the original. Scale that length.",
    formula: "\\[\\frac{a_1}{a_2} = \\frac{b_1}{b_2} = \\frac{c_1}{c_2}\\]",
    lesson: "Similar triangles have the same angles, and their matching sides are proportional. One scale factor applies to every pair of corresponding sides, including the longest sides. Identify which sides match before you multiply.",
    learnUrl: "https://www.mathsisfun.com/geometry/triangles-similar.html",
    learnLabel: "Math is Fun: Similar Triangles"
  },
  {
    id: "geo-sine",
    topic: "geometry",
    difficulty: "medium",
    prompt: "In a right triangle, the side opposite an acute angle is \\(3\\) and the hypotenuse is \\(5\\). What is the sine of that angle?",
    choices: ["\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{4}{5}\\)", "\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{5}{3}\\)"],
    correct: 0,
    displayAnswer: "\\(\\dfrac{3}{5}\\)",
    explanation: "Sine is opposite over hypotenuse, so \\(3/5\\). Cosine and tangent use a different side.",
    hint: "Divide the opposite side by the hypotenuse.",
    formula: "\\[\\sin \\theta = \\frac{\\text{opposite}}{\\text{hypotenuse}}\\]",
    lesson: "In a right triangle, sine of an acute angle is the length of the opposite side divided by the hypotenuse. Cosine uses the adjacent side over the hypotenuse, and tangent uses opposite over adjacent. A simplified fraction is an exact answer, and the decimal form of that same fraction is the same value.",
    learnUrl: "https://www.mathsisfun.com/sine-cosine-tangent.html",
    learnLabel: "Math is Fun: Sine, Cosine and Tangent"
  },
  {
    id: "calc-power-cubic",
    topic: "calculus",
    difficulty: "easy",
    prompt: "Find the derivative of \\(x^3\\).",
    choices: ["\\(3x^2\\)", "\\(x^2\\)", "\\(3x^3\\)", "\\(\\dfrac{x^4}{4}\\)"],
    correct: 0,
    displayAnswer: "\\(3x^2\\)",
    explanation: "Bring the exponent down and reduce the power by one: \\(3x^{2}\\).",
    hint: "Bring the exponent down in front, then reduce the power by one.",
    formula: "\\[\\frac{d}{dx} x^n = n x^{n-1}\\]",
    lesson: "The power rule says the derivative of x to the n is n times x to the n minus 1. The exponent comes down as a coefficient, and the power left behind is one smaller. A constant in front of a power is multiplied by that new coefficient.",
    learnUrl: "https://www.mathsisfun.com/calculus/derivatives-rules.html",
    learnLabel: "Math is Fun: Derivative Rules"
  },
  {
    id: "calc-power-fourth",
    topic: "calculus",
    difficulty: "easy",
    prompt: "Find the derivative of \\(5x^4\\).",
    choices: ["\\(20x^3\\)", "\\(5x^3\\)", "\\(20x^4\\)", "\\(4x^3\\)"],
    correct: 0,
    displayAnswer: "\\(20x^3\\)",
    explanation: "Multiply the coefficient by the exponent, then reduce the power: \\(5 \\times 4 \\, x^{3} = 20x^3\\).",
    hint: "Multiply the coefficient by the exponent, then reduce the exponent by one.",
    formula: "\\[\\frac{d}{dx} (c x^n) = c n x^{n-1}\\]",
    lesson: "Coefficients stay in the product when you use the power rule. Multiply the original coefficient by the old exponent, then reduce the exponent by one. The derivative of a plain constant term is zero, which is why constants disappear.",
    learnUrl: "https://www.mathsisfun.com/calculus/derivatives-rules.html",
    learnLabel: "Math is Fun: Derivative Rules"
  },
  {
    id: "calc-polynomial",
    topic: "calculus",
    difficulty: "medium",
    prompt: "Find the derivative of \\(4x^2 - 3x + 7\\).",
    choices: ["\\(8x - 3\\)", "\\(8x + 4\\)", "\\(4x - 3\\)", "\\(8x + 3\\)"],
    correct: 0,
    displayAnswer: "\\(8x - 3\\)",
    explanation: "Term by term, \\(4x^2\\) becomes \\(8x\\) and \\(-3x\\) becomes \\(-3\\). The constant 7 drops out, leaving \\(8x - 3\\).",
    hint: "Differentiate each term separately. Drop the constant term.",
    formula: "\\[\\frac{d}{dx}(ax^2 + bx + c) = 2ax + b\\]",
    lesson: "Differentiate a polynomial one term at a time and add the results. Each power uses the power rule, and the derivative of a constant is zero. The answer is usually a simpler polynomial, one degree lower than the original.",
    learnUrl: "https://www.mathsisfun.com/calculus/derivatives-rules.html",
    learnLabel: "Math is Fun: Derivative Rules"
  },
  {
    id: "calc-product",
    topic: "calculus",
    difficulty: "medium",
    prompt: "Find the derivative of \\(x(x^2 + 1)\\).",
    choices: ["\\(3x^2 + 1\\)", "\\(x^2 + 1\\)", "\\(2x^2\\)", "\\(x^3 + x\\)"],
    correct: 0,
    displayAnswer: "\\(3x^2 + 1\\)",
    explanation: "Product rule: \\(1 \\cdot (x^2+1) + x \\cdot 2x = x^2 + 1 + 2x^2\\). Combine like terms to get \\(3x^2 + 1\\).",
    hint: "Derivative of the first times the second, plus the first times the derivative of the second. Then combine like terms.",
    formula: "\\[(fg)' = f'g + fg'\\]",
    lesson: "The product rule is for a product of functions, not a single power. Differentiate the first factor and multiply by the untouched second factor, then add the first factor times the derivative of the second. Simplify by combining like terms after you expand.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/ProductQuotientRule.aspx",
    learnLabel: "Paul's Online Math Notes: Product and Quotient Rule"
  },
  {
    id: "calc-chain",
    topic: "calculus",
    difficulty: "medium",
    prompt: "Find the derivative of \\((2x + 1)^2\\).",
    choices: ["\\(8x + 4\\)", "\\(2(2x + 1)\\)", "\\(4(2x + 1)^2\\)", "\\((2x + 1)^2\\)"],
    correct: 0,
    displayAnswer: "\\(8x + 4\\)",
    explanation: "The outer derivative is \\(2(2x+1)\\), and the inside derivative is 2. Multiply them: \\(2(2x+1) \\cdot 2 = 8x+4\\).",
    hint: "Differentiate the outer power, keep the inside, and multiply by the derivative of the inside.",
    formula: "\\[\\frac{d}{dx} f(g(x)) = f'(g(x)) \\, g'(x)\\]",
    lesson: "The chain rule handles a function inside another function. Differentiate the outside and leave the inside as it is, then multiply by the derivative of the inside. For a power of a binomial, the outside derivative brings down the exponent and the inside contributes its own derivative.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/ChainRule.aspx",
    learnLabel: "Paul's Online Math Notes: Chain Rule"
  },
  {
    id: "calc-integral-linear",
    topic: "calculus",
    difficulty: "easy",
    prompt: "Evaluate the definite integral.\n\\[\\int_0^3 2x \\, dx\\]",
    choices: ["\\(9\\)", "\\(6\\)", "\\(18\\)", "\\(3\\)"],
    correct: 0,
    displayAnswer: "\\(9\\)",
    explanation: "An antiderivative of \\(2x\\) is \\(x^2\\). From 0 to 3 that is \\(9 - 0 = 9\\).",
    hint: "Find an antiderivative, then subtract its value at the lower limit from its value at the upper limit.",
    formula: "\\[\\int_a^b f(x) \\, dx = F(b) - F(a)\\]",
    lesson: "A definite integral equals the antiderivative at the right endpoint minus the antiderivative at the left endpoint. Find any antiderivative first, then evaluate it at the two limits. The constant of integration cancels in that subtraction, so you can take it to be zero.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/ComputingDefiniteIntegrals.aspx",
    learnLabel: "Paul's Online Math Notes: Computing Definite Integrals"
  },
  {
    id: "calc-integral-square",
    topic: "calculus",
    difficulty: "medium",
    prompt: "Evaluate the definite integral.\n\\[\\int_0^2 x^2 \\, dx\\]",
    choices: ["\\(\\dfrac{8}{3}\\)", "\\(8\\)", "\\(4\\)", "\\(\\dfrac{4}{3}\\)"],
    correct: 0,
    displayAnswer: "\\(\\dfrac{8}{3}\\)",
    explanation: "An antiderivative of \\(x^2\\) is \\(x^3/3\\). From 0 to 2 that is \\(8/3\\).",
    hint: "Raise the power by one and divide by the new power, then evaluate between the limits.",
    formula: "\\[\\int x^n \\, dx = \\frac{x^{n+1}}{n+1} + C \\quad (n \\neq -1)\\]",
    lesson: "The power rule for integrals raises the exponent by one and divides by the new exponent. Evaluate that antiderivative at the upper limit and subtract the value at the lower limit. An exact fraction is preferable to a rounded decimal.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/ComputingDefiniteIntegrals.aspx",
    learnLabel: "Paul's Online Math Notes: Computing Definite Integrals"
  },
  {
    id: "calc-integral-bounds",
    topic: "calculus",
    difficulty: "medium",
    prompt: "Evaluate the definite integral.\n\\[\\int_1^2 3x^2 \\, dx\\]",
    choices: ["\\(7\\)", "\\(8\\)", "\\(9\\)", "\\(12\\)"],
    correct: 0,
    displayAnswer: "\\(7\\)",
    explanation: "An antiderivative of \\(3x^2\\) is \\(x^3\\). Upper minus lower is \\(8 - 1 = 7\\).",
    hint: "The lower limit is not zero, so evaluate the antiderivative at both ends and subtract.",
    formula: "\\[\\int_a^b f(x) \\, dx = F(b) - F(a)\\]",
    lesson: "When the lower limit is not zero, the antiderivative at that limit is not automatically zero. Compute the antiderivative at both ends and subtract in the order upper minus lower. A coefficient in front of a power is included when you find the antiderivative.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/ComputingDefiniteIntegrals.aspx",
    learnLabel: "Paul's Online Math Notes: Computing Definite Integrals"
  },
  {
    id: "calc-limit",
    topic: "calculus",
    difficulty: "medium",
    prompt: "Evaluate the limit.\n\\[\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}\\]",
    choices: ["\\(4\\)", "\\(0\\)", "\\(2\\)", "\\(\\text{does not exist}\\)"],
    correct: 0,
    displayAnswer: "\\(4\\)",
    explanation: "Factor \\(x^2-4 = (x-2)(x+2)\\) and cancel \\(x-2\\). The simplified limit is \\(2+2 = 4\\).",
    hint: "Direct substitution makes the denominator zero. Factor the numerator and cancel before you substitute.",
    formula: "\\[\\lim_{x \\to a} f(x) = L\\]",
    lesson: "A limit asks for the value the expression approaches, which may exist even when direct substitution gives zero divided by zero. Factor and cancel the common factor that made the denominator zero, then substitute. After canceling, the simplified function agrees with the original everywhere except at that one point.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/LimitsIntro.aspx",
    learnLabel: "Paul's Online Math Notes: Limits"
  },
  {
    id: "calc-tangent-slope",
    topic: "calculus",
    difficulty: "easy",
    prompt: "What is the slope of the tangent line to \\(f(x) = x^2\\) at \\(x = 3\\)?",
    choices: ["\\(6\\)", "\\(9\\)", "\\(2x\\)", "\\(3\\)"],
    correct: 0,
    displayAnswer: "\\(6\\)",
    explanation: "The derivative \\(f'(x) = 2x\\) is the slope of the tangent. At \\(x = 3\\), that slope is 6.",
    hint: "Differentiate to get a formula for the slope, then substitute the given x-value.",
    formula: "\\[f'(a) = \\lim_{h \\to 0} \\frac{f(a + h) - f(a)}{h}\\]",
    lesson: "The derivative of a function at a point is the slope of the tangent line there. Differentiate the function first so you have a slope formula, then substitute the x-value of the point. The y-value of the point is not required when the question only asks for the slope.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/CalcI/Tangents_Rates.aspx",
    learnLabel: "Paul's Online Math Notes: Tangents and Rates of Change"
  },
  {
    id: "alg-ineq-basic",
    topic: "algebra",
    difficulty: "easy",
    prompt: "Solve for \\(x\\): \\(3x - 4 < 11\\).",
    choices: ["\\(x < 5\\)", "\\(x > 5\\)", "\\(x < 15\\)", "\\(x < 7\\)"],
    correct: 0,
    displayAnswer: "\\(x < 5\\)",
    explanation: "Add 4 to both sides: \\(3x < 15\\). Divide by 3 to get \\(x < 5\\).",
    hint: "Undo the subtraction first, then divide. The inequality sign stays as it is.",
    formula: "\\[ax + b < c \\quad\\Rightarrow\\quad x < \\frac{c - b}{a}\\quad (a > 0)\\]",
    lesson: "A linear inequality is solved like a linear equation, as long as you multiply or divide by a positive number. Do the same step to both sides and keep the inequality sign. The solution is a range of values, not a single number.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearInequalities.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Inequalities"
  },
  {
    id: "alg-power-of-power",
    topic: "algebra",
    difficulty: "easy",
    prompt: "Evaluate \\((3^2)^3\\).",
    choices: ["\\(729\\)", "\\(243\\)", "\\(81\\)", "\\(19683\\)"],
    correct: 0,
    displayAnswer: "\\(729\\)",
    explanation: "A power of a power multiplies the exponents: \\(3^{2 \\cdot 3} = 3^6\\). Then \\(3^6 = 729\\).",
    hint: "Multiply the exponents, then evaluate that single power of 3.",
    formula: "\\[(a^m)^n = a^{mn}\\]",
    lesson: "When a power is raised to another power, keep the base and multiply the exponents. That is different from multiplying two powers, where you add the exponents. Evaluate the combined power once the exponents are simplified.",
    learnUrl: "https://www.mathsisfun.com/algebra/exponent-laws.html",
    learnLabel: "Math is Fun: Exponent Laws"
  },
  {
    id: "alg-word-notebooks",
    topic: "algebra",
    difficulty: "easy",
    prompt: "A notebook costs 4 dollars. Maya buys 3 notebooks and a pen that costs 2 dollars. How many dollars does she spend?",
    choices: ["\\(14\\)", "\\(12\\)", "\\(18\\)", "\\(10\\)"],
    correct: 0,
    displayAnswer: "\\(14\\)",
    explanation: "Three notebooks cost \\(3 \\times 4 = 12\\) dollars. Adding the 2-dollar pen gives \\(12 + 2 = 14\\).",
    hint: "Find the cost of the notebooks first, then add the pen.",
    formula: "\\[\\text{total} = (\\text{price})(\\text{count}) + \\text{extra}\\]",
    lesson: "A total-cost problem multiplies each price by how many of that item you buy, then adds the pieces. Units stay in dollars if every price was in dollars. Substituting the given counts is enough; there is no unknown left to solve for.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-distribute-neg",
    topic: "algebra",
    difficulty: "easy",
    prompt: "Expand \\(-2(x - 5)\\).",
    choices: ["\\(-2x + 10\\)", "\\(-2x - 10\\)", "\\(-2x + 5\\)", "\\(2x - 10\\)"],
    correct: 0,
    displayAnswer: "\\(-2x + 10\\)",
    explanation: "Multiply each term by \\(-2\\): \\(-2 \\cdot x = -2x\\) and \\(-2 \\cdot (-5) = 10\\). The expansion is \\(-2x + 10\\).",
    hint: "Multiply the number outside by each term inside. A negative times a negative is positive.",
    formula: "\\[a(b - c) = ab - ac\\]",
    lesson: "The distributive property multiplies the factor outside the parentheses by every term inside. Signs travel with those terms. A negative factor flips the sign of each product, so a subtracted term inside can become added after expansion.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-prop-basic",
    topic: "algebra",
    difficulty: "easy",
    prompt: "Solve for \\(x\\): \\(\\dfrac{x}{4} = 6\\).",
    choices: ["\\(x = 24\\)", "\\(x = 10\\)", "\\(x = \\dfrac{3}{2}\\)", "\\(x = 12\\)"],
    correct: 0,
    displayAnswer: "\\(x = 24\\)",
    explanation: "Multiply both sides by 4: \\(x = 6 \\cdot 4 = 24\\).",
    hint: "The variable is divided by 4. Multiply both sides by that divisor.",
    formula: "\\[\\frac{x}{a} = b \\quad\\Rightarrow\\quad x = ab\\]",
    lesson: "Division and multiplication undo each other. If a variable is divided by a number, multiply both sides by that number to isolate it. Check by dividing your answer by the original divisor.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-diff-squares",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Factor \\(x^2 - 9\\).",
    choices: ["\\((x - 3)(x + 3)\\)", "\\((x - 9)(x + 1)\\)", "\\((x - 3)^2\\)", "\\((x + 3)^2\\)"],
    correct: 0,
    displayAnswer: "\\((x - 3)(x + 3)\\)",
    explanation: "This is a difference of squares: \\(x^2 - 3^2 = (x - 3)(x + 3)\\).",
    hint: "Both terms are squares and they are subtracted. Use the difference-of-squares pattern.",
    formula: "\\[a^2 - b^2 = (a - b)(a + b)\\]",
    lesson: "A difference of squares factors into a pair of conjugates: the same two terms, one subtracted and one added. There is no middle term to match. Squaring a binomial instead would produce a middle term, so that pattern does not fit here.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/Factoring.aspx",
    learnLabel: "Paul's Online Math Notes: Factoring"
  },
  {
    id: "alg-ineq-flip",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Solve for \\(x\\): \\(-2x + 1 \\ge 7\\).",
    choices: ["\\(x \\le -3\\)", "\\(x \\ge -3\\)", "\\(x \\le 3\\)", "\\(x \\le -4\\)"],
    correct: 0,
    displayAnswer: "\\(x \\le -3\\)",
    explanation: "Subtract 1: \\(-2x \\ge 6\\). Divide by \\(-2\\) and reverse the sign to get \\(x \\le -3\\).",
    hint: "When you divide by a negative number, reverse the inequality sign.",
    formula: "\\[\\text{If } a < 0 \\text{ and } ax \\ge b, \\text{ then } x \\le \\frac{b}{a}.\\]",
    lesson: "Adding or subtracting the same amount never flips an inequality. Multiplying or dividing by a negative number does, because it reverses the order of the number line. After you isolate the variable, check a value on each side of the boundary.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearInequalities.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Inequalities"
  },
  {
    id: "alg-system-add",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Solve the system \\(2x + y = 7\\) and \\(x - y = 2\\).",
    choices: ["\\(x = 3,\\; y = 1\\)", "\\(x = 3,\\; y = 4\\)", "\\(x = 1,\\; y = 5\\)", "\\(x = 2,\\; y = 3\\)"],
    correct: 0,
    displayAnswer: "\\(x = 3,\\; y = 1\\)",
    explanation: "Add the equations: \\(3x = 9\\), so \\(x = 3\\). Then \\(3 - y = 2\\), so \\(y = 1\\).",
    hint: "The y coefficients are opposites. Add the equations to eliminate y.",
    formula: "\\[\\begin{aligned} ax + by &= c \\\\ dx + ey &= f \\end{aligned}\\]",
    lesson: "Elimination adds or subtracts equations so one variable disappears. It works immediately when a pair of coefficients is already opposite. Substitute the value you find back into either original equation for the other variable, and check the pair in both equations.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx",
    learnLabel: "Paul's Online Math Notes: Systems of Equations"
  },
  {
    id: "alg-neg-exp",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Evaluate \\(2^{-3}\\).",
    choices: ["\\(\\dfrac{1}{8}\\)", "\\(-8\\)", "\\(-6\\)", "\\(8\\)"],
    correct: 0,
    displayAnswer: "\\(\\dfrac{1}{8}\\)",
    explanation: "A negative exponent means a reciprocal: \\(2^{-3} = \\dfrac{1}{2^3} = \\dfrac{1}{8}\\).",
    hint: "A negative exponent does not make the value negative. Take the reciprocal of the positive power.",
    formula: "\\[a^{-n} = \\frac{1}{a^n}\\quad (a \\neq 0)\\]",
    lesson: "A negative exponent says how many times to divide by the base, which is the same as a reciprocal of a positive power. The sign of the exponent is not the sign of the result. The base stays positive here, so the value is a positive fraction.",
    learnUrl: "https://www.mathsisfun.com/algebra/exponent-laws.html",
    learnLabel: "Math is Fun: Exponent Laws"
  },
  {
    id: "alg-word-age",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Sam's age is 4 years more than twice his sister's age. His sister is 6. How old is Sam?",
    choices: ["\\(16\\)", "\\(12\\)", "\\(10\\)", "\\(20\\)"],
    correct: 0,
    displayAnswer: "\\(16\\)",
    explanation: "Twice his sister's age is \\(2 \\times 6 = 12\\). Four more than that is \\(12 + 4 = 16\\).",
    hint: "Translate 'twice' as multiplication and 'more than' as addition. The sister's age is the known number.",
    formula: "\\[\\text{age} = 2(\\text{sister}) + 4\\]",
    lesson: "Age statements turn into expressions by reading the operations in order. 'Twice a number' is 2 times that number, and '4 more than' adds 4 afterward. Substitute the given age and simplify from the inside out.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-sq-diff-solve",
    topic: "algebra",
    difficulty: "medium",
    prompt: "Solve \\(x^2 - 4 = 0\\).",
    choices: ["\\(x = 2\\) or \\(x = -2\\)", "\\(x = 4\\) or \\(x = -4\\)", "\\(x = 2\\)", "\\(x = -4\\)"],
    correct: 0,
    displayAnswer: "\\(x = 2\\) or \\(x = -2\\)",
    explanation: "Add 4 and take square roots: \\(x^2 = 4\\), so \\(x = 2\\) or \\(x = -2\\).",
    hint: "Isolate the square, then remember that both a positive and a negative square root satisfy it.",
    formula: "\\[x^2 = a \\quad\\Rightarrow\\quad x = \\pm \\sqrt{a}\\quad (a > 0)\\]",
    lesson: "Every positive number has two square roots, equal in size and opposite in sign. After you isolate a squared variable, write both roots. Zero has one square root, and a negative number has none in the real numbers.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "alg-write-line",
    topic: "algebra",
    difficulty: "medium",
    prompt: "A line has slope \\(3\\) and passes through \\((0, -1)\\). What is its equation?",
    choices: ["\\(y = 3x - 1\\)", "\\(y = 3x + 1\\)", "\\(y = -x + 3\\)", "\\(y = 3x\\)"],
    correct: 0,
    displayAnswer: "\\(y = 3x - 1\\)",
    explanation: "Slope-intercept form is \\(y = mx + b\\). Here \\(m = 3\\) and the y-intercept is \\(-1\\), so \\(y = 3x - 1\\).",
    hint: "The y-intercept is the y-value where x is 0. It is the constant term in slope-intercept form.",
    formula: "\\[y = mx + b\\]",
    lesson: "Slope-intercept form names the slope as m and the y-intercept as b. A point with x-coordinate 0 sits on the y-axis, so its y-coordinate is b. Keep the sign of that intercept when you write the equation.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/Lines.aspx",
    learnLabel: "Paul's Online Math Notes: Lines"
  },
  {
    id: "alg-system-scale",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Solve the system \\(2x + 3y = 12\\) and \\(4x - y = 10\\).",
    choices: ["\\(x = 3,\\; y = 2\\)", "\\(x = 2,\\; y = 3\\)", "\\(x = 4,\\; y = 2\\)", "\\(x = 3,\\; y = 1\\)"],
    correct: 0,
    displayAnswer: "\\(x = 3,\\; y = 2\\)",
    explanation: "Multiply the second equation by 3: \\(12x - 3y = 30\\). Add the first: \\(14x = 42\\), so \\(x = 3\\). Then \\(4(3) - y = 10\\), so \\(y = 2\\).",
    hint: "Scale one equation so the y terms become opposites, then add.",
    formula: "\\[\\begin{aligned} a_1 x + b_1 y &= c_1 \\\\ a_2 x + b_2 y &= c_2 \\end{aligned}\\]",
    lesson: "When no coefficients are opposites yet, multiply one equation by a constant so they are. Add to eliminate that variable, solve the resulting one-variable equation, and substitute back. The multiplier has to hit every term, including the constant.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx",
    learnLabel: "Paul's Online Math Notes: Systems of Equations"
  },
  {
    id: "alg-factor-ac",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Factor \\(2x^2 + 7x + 3\\).",
    choices: ["\\((2x + 1)(x + 3)\\)", "\\((2x + 3)(x + 1)\\)", "\\((2x - 1)(x - 3)\\)", "\\((x + 1)(x + 3)\\)"],
    correct: 0,
    displayAnswer: "\\((2x + 1)(x + 3)\\)",
    explanation: "Look for two numbers that multiply to \\(2 \\cdot 3 = 6\\) and add to 7, namely 1 and 6. Splitting the middle term gives \\((2x + 1)(x + 3)\\).",
    hint: "Because the leading coefficient is not 1, find a pair that multiplies to a times c and adds to b.",
    formula: "\\[ax^2 + bx + c = (px + q)(rx + s)\\]",
    lesson: "When the leading coefficient is not 1, a guess-and-check still has to produce both that leading term and the constant. The ac method finds a pair that multiplies to a times c and adds to b, then splits the middle term so the polynomial factors by grouping. Multiply the binomials back together to confirm.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/Factoring.aspx",
    learnLabel: "Paul's Online Math Notes: Factoring"
  },
  {
    id: "alg-quad-roots",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Solve \\(x^2 - 2x - 8 = 0\\).",
    choices: ["\\(x = 4\\) or \\(x = -2\\)", "\\(x = -4\\) or \\(x = 2\\)", "\\(x = 8\\) or \\(x = -1\\)", "\\(x = 4\\) or \\(x = 2\\)"],
    correct: 0,
    displayAnswer: "\\(x = 4\\) or \\(x = -2\\)",
    explanation: "Factor the left side as \\((x - 4)(x + 2) = 0\\). The solutions are \\(x = 4\\) and \\(x = -2\\).",
    hint: "Find two numbers that multiply to -8 and add to -2, then set each factor equal to zero.",
    formula: "\\[x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}\\]",
    lesson: "A quadratic set equal to zero can be solved by factoring when a pair of numbers multiplies to the constant and adds to the middle coefficient. Each factor then contributes one root. The quadratic formula gives the same roots when you would rather not factor.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "alg-exp-combine",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Simplify \\(\\dfrac{3^{5}}{3^{2}} \\cdot 3^{-1}\\).",
    choices: ["\\(9\\)", "\\(27\\)", "\\(3\\)", "\\(81\\)"],
    correct: 0,
    displayAnswer: "\\(9\\)",
    explanation: "Subtract exponents in the quotient: \\(3^{5 - 2} = 3^3\\). Then \\(3^3 \\cdot 3^{-1} = 3^{2} = 9\\).",
    hint: "Use one exponent rule at a time. Same-base division subtracts exponents, and same-base multiplication adds them.",
    formula: "\\[\\frac{a^m}{a^n} \\cdot a^{k} = a^{m - n + k}\\]",
    lesson: "Powers with the same base combine by adding exponents when you multiply and subtracting them when you divide. A negative exponent is just another term in that sum. Simplify the exponent fully before you evaluate the power.",
    learnUrl: "https://www.mathsisfun.com/algebra/exponent-laws.html",
    learnLabel: "Math is Fun: Exponent Laws"
  },
  {
    id: "alg-ineq-frac",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Solve for \\(x\\): \\(\\dfrac{x - 1}{2} > 3\\).",
    choices: ["\\(x > 7\\)", "\\(x > 6\\)", "\\(x > 5\\)", "\\(x < 7\\)"],
    correct: 0,
    displayAnswer: "\\(x > 7\\)",
    explanation: "Multiply both sides by 2: \\(x - 1 > 6\\). Add 1 to get \\(x > 7\\).",
    hint: "The denominator is positive, so multiplying both sides by it does not flip the inequality.",
    formula: "\\[\\frac{x - b}{a} > c \\quad\\Rightarrow\\quad x > ac + b\\quad (a > 0)\\]",
    lesson: "Clear a positive denominator by multiplying both sides, and the inequality sign stays put. Then undo whatever is still done to the variable. A negative denominator would reverse the sign, so the sign of the divisor matters.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearInequalities.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Inequalities"
  },
  {
    id: "alg-word-pens",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Maya buys pens for 3 dollars each and pencils for 1 dollar each. She buys 10 items and spends 18 dollars. How many pens does she buy?",
    choices: ["\\(4\\)", "\\(6\\)", "\\(2\\)", "\\(8\\)"],
    correct: 0,
    displayAnswer: "\\(4\\)",
    explanation: "Let \\(p\\) be the number of pens. Then \\(3p + 1(10 - p) = 18\\), so \\(2p + 10 = 18\\) and \\(p = 4\\).",
    hint: "If p is the number of pens, the number of pencils is 10 minus p. Write the cost of both.",
    formula: "\\[3p + 1(10 - p) = 18\\]",
    lesson: "Two unknowns with a fixed total can be written with one variable. Express the second count as the total minus the first, then build the cost equation. Solve that linear equation and check that the counts are non-negative and add to the given total.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "alg-word-sumdiff",
    topic: "algebra",
    difficulty: "hard",
    prompt: "Two numbers add to 20 and differ by 6. What is the larger number?",
    choices: ["\\(13\\)", "\\(7\\)", "\\(14\\)", "\\(10\\)"],
    correct: 0,
    displayAnswer: "\\(13\\)",
    explanation: "Let the numbers be \\(x\\) and \\(y\\), with \\(x + y = 20\\) and \\(x - y = 6\\). Adding those equations gives \\(2x = 26\\), so \\(x = 13\\).",
    hint: "Call the larger number x. Then x plus the smaller is 20, and x minus the smaller is 6.",
    formula: "\\[\\begin{aligned} x + y &= s \\\\ x - y &= d \\end{aligned} \\quad\\Rightarrow\\quad x = \\frac{s + d}{2}\\]",
    lesson: "A sum and a difference are a two-equation system. Adding them cancels the smaller number and doubles the larger one. Half of that sum is the larger number, and it should exceed the smaller by the given difference.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx",
    learnLabel: "Paul's Online Math Notes: Systems of Equations"
  },
  {
    id: "alg-word-area",
    topic: "algebra",
    difficulty: "hard",
    prompt: "A rectangle's length is 3 more than its width, and its area is 40. What is the width?",
    choices: ["\\(5\\)", "\\(8\\)", "\\(4\\)", "\\(10\\)"],
    correct: 0,
    displayAnswer: "\\(5\\)",
    explanation: "If the width is \\(w\\), then \\(w(w + 3) = 40\\), or \\(w^2 + 3w - 40 = 0\\). Factoring gives \\((w + 8)(w - 5) = 0\\). The positive width is 5.",
    hint: "Let the width be w. Then the length is w + 3, and their product is the area.",
    formula: "\\[w(w + 3) = A\\]",
    lesson: "A rectangle area equation is quadratic when one side is described in terms of the other. Expand, bring every term to one side, and factor or use the quadratic formula. A length has to be positive, so discard a negative root.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "gmat-sale",
    topic: "gmat",
    difficulty: "easy",
    prompt: "A shirt priced at $80 is discounted by 25%. What is the sale price?",
    choices: ["\\(\\$60\\)", "\\(\\$55\\)", "\\(\\$20\\)", "\\(\\$64\\)", "\\(\\$75\\)"],
    correct: 0,
    displayAnswer: "\\(\\$60\\)",
    explanation: "A 25% discount leaves 75% of the price. \\(0.75 \\times 80 = 60\\), so the sale price is $60.",
    hint: "Subtract the discount rate from 100%, then multiply that percent by the original price.",
    formula: "\\[\\text{sale} = \\text{original} \\times (1 - r)\\]",
    lesson: "A percent discount is a fraction of the original price removed, not a subtraction of the percent number itself. The sale price is the original times one minus the discount rate. The amount saved and the price you pay are different quantities.",
    learnUrl: "https://www.mathsisfun.com/percentage.html",
    learnLabel: "Math is Fun: Introduction to Percentages"
  },
  {
    id: "gmat-ratio-marbles",
    topic: "gmat",
    difficulty: "easy",
    prompt: "The ratio of red marbles to blue marbles is \\(2 : 3\\). There are 10 red marbles. How many blue marbles are there?",
    choices: ["\\(15\\)", "\\(12\\)", "\\(6\\)", "\\(20\\)", "\\(30\\)"],
    correct: 0,
    displayAnswer: "\\(15\\)",
    explanation: "Red to blue is \\(2 : 3\\), and red is 10, so each part is \\(10 / 2 = 5\\). Blue is \\(3 \\times 5 = 15\\).",
    hint: "Find the value of one ratio part from the red marbles, then scale the blue part.",
    formula: "\\[\\frac{a_1}{b_1} = \\frac{a_2}{b_2}\\]",
    lesson: "A ratio compares parts of the same whole. If you know one quantity, divide it by its number of parts to find the size of one part, then multiply by the other number of parts. Cross-multiplication on the two fractions gives the same result.",
    learnUrl: "https://www.mathsisfun.com/numbers/ratio.html",
    learnLabel: "Math is Fun: Ratios"
  },
  {
    id: "gmat-mean",
    topic: "gmat",
    difficulty: "easy",
    prompt: "What is the average (arithmetic mean) of 4, 8, and 12?",
    choices: ["\\(8\\)", "\\(6\\)", "\\(12\\)", "\\(24\\)", "\\(4\\)"],
    correct: 0,
    displayAnswer: "\\(8\\)",
    explanation: "Add the values and divide by how many there are: \\((4 + 8 + 12) / 3 = 24 / 3 = 8\\).",
    hint: "Add the three numbers, then divide by 3.",
    formula: "\\[\\text{mean} = \\frac{\\text{sum}}{\\text{count}}\\]",
    lesson: "The arithmetic mean is the sum of the values divided by the number of values. The sum itself is larger than the mean, and the mean of a short list sits between the least and greatest values when those values are not all equal.",
    learnUrl: "https://www.mathsisfun.com/mean.html",
    learnLabel: "Math is Fun: Mean"
  },
  {
    id: "gmat-percent-of",
    topic: "gmat",
    difficulty: "easy",
    prompt: "What is 15% of 200?",
    choices: ["\\(30\\)", "\\(15\\)", "\\(3\\)", "\\(300\\)", "\\(20\\)"],
    correct: 0,
    displayAnswer: "\\(30\\)",
    explanation: "Fifteen percent is \\(0.15\\). Then \\(0.15 \\times 200 = 30\\).",
    hint: "Convert the percent to a decimal or a fraction, then multiply by 200.",
    formula: "\\[p\\% \\text{ of } n = \\frac{p}{100} \\cdot n\\]",
    lesson: "Percent means per hundred, so 15% is 15/100. 'Of' in this setting means multiplication. Multiplying by the percent without dividing by 100 makes the result a hundred times too large.",
    learnUrl: "https://www.mathsisfun.com/percentage.html",
    learnLabel: "Math is Fun: Introduction to Percentages"
  },
  {
    id: "gmat-speed",
    topic: "gmat",
    difficulty: "easy",
    prompt: "A car travels 120 miles in 2 hours at a constant speed. What is that speed, in miles per hour?",
    choices: ["\\(60\\)", "\\(240\\)", "\\(40\\)", "\\(30\\)", "\\(120\\)"],
    correct: 0,
    displayAnswer: "\\(60\\)",
    explanation: "Speed is distance divided by time: \\(120 / 2 = 60\\) miles per hour.",
    hint: "Divide the distance by the time. The units are miles per hour.",
    formula: "\\[\\text{speed} = \\frac{\\text{distance}}{\\text{time}}\\]",
    lesson: "Constant speed is distance divided by time. Multiplying distance by time does not give speed. The units of the answer follow the units you divide, here miles divided by hours.",
    learnUrl: "https://www.mathsisfun.com/measure/speed-velocity.html",
    learnLabel: "Math is Fun: Speed and Velocity"
  },
  {
    id: "gmat-profit",
    topic: "gmat",
    difficulty: "easy",
    prompt: "An item costs $40 and sells for $50. The profit is what percent of the cost?",
    choices: ["\\(25\\%\\)", "\\(20\\%\\)", "\\(10\\%\\)", "\\(50\\%\\)", "\\(40\\%\\)"],
    correct: 0,
    displayAnswer: "\\(25\\%\\)",
    explanation: "Profit is \\(50 - 40 = 10\\) dollars. As a percent of the cost, \\(10 / 40 = 0.25 = 25\\%\\).",
    hint: "Profit is selling price minus cost. Divide that profit by the cost, not by the selling price.",
    formula: "\\[\\text{percent profit} = \\frac{\\text{selling price} - \\text{cost}}{\\text{cost}} \\times 100\\%\\]",
    lesson: "Profit percent needs a base. When the question says 'of the cost,' the cost is the denominator. Dividing the same profit by the selling price answers a different question. Convert the resulting decimal to a percent by multiplying by 100.",
    learnUrl: "https://www.mathsisfun.com/percentage.html",
    learnLabel: "Math is Fun: Introduction to Percentages"
  },
  {
    id: "gmat-fraction-add",
    topic: "gmat",
    difficulty: "easy",
    prompt: "What is \\(\\dfrac{3}{4} + \\dfrac{1}{8}\\)?",
    choices: ["\\(\\dfrac{7}{8}\\)", "\\(\\dfrac{4}{12}\\)", "\\(1\\)", "\\(\\dfrac{3}{8}\\)", "\\(\\dfrac{1}{2}\\)"],
    correct: 0,
    displayAnswer: "\\(\\dfrac{7}{8}\\)",
    explanation: "Write \\(\\dfrac{3}{4}\\) as \\(\\dfrac{6}{8}\\). Then \\(\\dfrac{6}{8} + \\dfrac{1}{8} = \\dfrac{7}{8}\\).",
    hint: "Use a common denominator of 8 before you add the numerators.",
    formula: "\\[\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}\\]",
    lesson: "Fractions add only after their denominators match. Convert each fraction, add the numerators, and keep the common denominator. Adding the numerators and the denominators separately is not the rule for fraction addition.",
    learnUrl: "https://www.mathsisfun.com/fractions_addition.html",
    learnLabel: "Math is Fun: Adding Fractions"
  },
  {
    id: "gmat-work",
    topic: "gmat",
    difficulty: "medium",
    prompt: "Machine A fills a tank in 6 hours. Machine B fills the same tank in 3 hours. How long do they take to fill the tank working together?",
    choices: ["\\(2\\) hours", "\\(4.5\\) hours", "\\(9\\) hours", "\\(1\\) hour", "\\(4\\) hours"],
    correct: 0,
    displayAnswer: "\\(2\\) hours",
    explanation: "The combined rate is \\(\\dfrac{1}{6} + \\dfrac{1}{3} = \\dfrac{1}{2}\\) tank per hour. The time is the reciprocal, 2 hours.",
    hint: "Add the two rates in tanks per hour. The time is 1 divided by that combined rate.",
    formula: "\\[\\frac{1}{t} = \\frac{1}{t_1} + \\frac{1}{t_2}\\]",
    lesson: "Work-rate problems add the fraction of the job each worker finishes in one hour. Times themselves do not add. Once the combined rate is known, the time to finish one job is the reciprocal of that rate.",
    learnUrl: "https://www.mathsisfun.com/algebra/word-questions-solving.html",
    learnLabel: "Math is Fun: Solving Word Questions"
  },
  {
    id: "gmat-clubs",
    topic: "gmat",
    difficulty: "medium",
    prompt: "A class has 40 students, and 30% of them are in the math club. One third of the math club is also in the science club. How many students are in both clubs?",
    choices: ["\\(4\\)", "\\(12\\)", "\\(10\\)", "\\(8\\)", "\\(13\\)"],
    correct: 0,
    displayAnswer: "\\(4\\)",
    explanation: "The math club has \\(0.30 \\times 40 = 12\\) students. One third of 12 is 4, so 4 students are in both clubs.",
    hint: "Find the math-club count first. The overlap is a fraction of that count, not of the whole class.",
    formula: "\\[\\text{overlap} = \\left(\\text{fraction}\\right)\\left(\\text{group}\\right)\\]",
    lesson: "Read which group a percent or fraction applies to. Here the one-third applies only to the math club, and the 30% applies to the class. Compute the inner group first, then take the fraction of it.",
    learnUrl: "https://www.mathsisfun.com/sets/venn-diagrams.html",
    learnLabel: "Math is Fun: Venn Diagrams"
  },
  {
    id: "gmat-consecutive",
    topic: "gmat",
    difficulty: "medium",
    prompt: "The sum of three consecutive integers is 72. What is the largest of the three?",
    choices: ["\\(25\\)", "\\(24\\)", "\\(26\\)", "\\(23\\)", "\\(27\\)"],
    correct: 0,
    displayAnswer: "\\(25\\)",
    explanation: "Let the integers be \\(n\\), \\(n + 1\\), and \\(n + 2\\). Then \\(3n + 3 = 72\\), so \\(n = 23\\). The largest is \\(25\\).",
    hint: "Call the smallest integer n. The next two are n + 1 and n + 2, and their sum is 72.",
    formula: "\\[n + (n + 1) + (n + 2) = 3n + 3\\]",
    lesson: "Consecutive integers differ by 1. Naming the smallest one determines the other two, and their sum is three times the smallest plus a small constant. Solve for the smallest, then step forward to the one the question asks for.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "gmat-trip-time",
    topic: "gmat",
    difficulty: "medium",
    prompt: "A train travels 120 miles at 60 miles per hour, then 60 miles at 20 miles per hour. How many hours does the whole trip take?",
    choices: ["\\(5\\) hours", "\\(4.5\\) hours", "\\(3\\) hours", "\\(2\\) hours", "\\(6\\) hours"],
    correct: 0,
    displayAnswer: "\\(5\\) hours",
    explanation: "The first leg takes \\(120 / 60 = 2\\) hours and the second takes \\(60 / 20 = 3\\) hours. The total time is \\(2 + 3 = 5\\) hours.",
    hint: "Find the time for each leg separately, then add those times. Do not average the speeds first.",
    formula: "\\[t = \\frac{d_1}{r_1} + \\frac{d_2}{r_2}\\]",
    lesson: "Time is distance divided by speed, and times from successive legs add. Averaging the two speeds and dividing the total distance by that average is a different calculation, and it matches the real total time only in special cases.",
    learnUrl: "https://www.mathsisfun.com/measure/speed-velocity.html",
    learnLabel: "Math is Fun: Speed and Velocity"
  },
  {
    id: "gmat-marble-prob",
    topic: "gmat",
    difficulty: "medium",
    prompt: "A bag has 3 red marbles and 2 blue marbles. One marble is drawn at random. What is the probability that it is red?",
    choices: ["\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{2}{5}\\)", "\\(\\dfrac{3}{2}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{5}{3}\\)"],
    correct: 0,
    displayAnswer: "\\(\\dfrac{3}{5}\\)",
    explanation: "There are \\(3 + 2 = 5\\) equally likely marbles, and 3 are red. The probability is \\(\\dfrac{3}{5}\\).",
    hint: "Divide the number of red marbles by the total number of marbles.",
    formula: "\\[P(\\text{event}) = \\frac{\\text{favorable}}{\\text{total}}\\]",
    lesson: "For one draw from equally likely outcomes, the probability is the count of favorable outcomes over the count of all outcomes. The answer is a number from 0 to 1, often left as a simplified fraction. Odds and probability are different comparisons.",
    learnUrl: "https://www.mathsisfun.com/data/probability.html",
    learnLabel: "Math is Fun: Probability"
  },
  {
    id: "gmat-percent-up",
    topic: "gmat",
    difficulty: "medium",
    prompt: "A price rises from $50 to $65. What is the percent increase?",
    choices: ["\\(30\\%\\)", "\\(15\\%\\)", "\\(23\\%\\)", "\\(65\\%\\)", "\\(50\\%\\)"],
    correct: 0,
    displayAnswer: "\\(30\\%\\)",
    explanation: "The increase is \\(65 - 50 = 15\\) dollars. Compared with the original price, \\(15 / 50 = 0.30 = 30\\%\\).",
    hint: "Divide the change by the original price, then convert that decimal to a percent.",
    formula: "\\[\\text{percent change} = \\frac{\\text{new} - \\text{original}}{\\text{original}} \\times 100\\%\\]",
    lesson: "Percent change uses the starting amount as the base. The dollar change is the numerator, not the percent itself. Dividing by the new price instead of the original price answers a different question.",
    learnUrl: "https://www.mathsisfun.com/percentage.html",
    learnLabel: "Math is Fun: Introduction to Percentages"
  },
  {
    id: "gmat-x-squared",
    topic: "gmat",
    difficulty: "medium",
    prompt: "If \\(2x + 5 = 17\\), what is \\(x^2\\)?",
    choices: ["\\(36\\)", "\\(6\\)", "\\(12\\)", "\\(144\\)", "\\(121\\)"],
    correct: 0,
    displayAnswer: "\\(36\\)",
    explanation: "Subtract 5 and divide by 2: \\(x = 6\\). Then \\(x^2 = 36\\).",
    hint: "Solve for x first. The question asks for the square of that value.",
    formula: "\\[ax + b = c \\quad\\Rightarrow\\quad x = \\frac{c - b}{a}\\]",
    lesson: "Read the quantity the question actually asks for. Solving the linear equation gives x, and a further squaring step gives x squared. Stopping at x, or squaring a different intermediate number, answers a nearby question.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "gmat-rect-area",
    topic: "gmat",
    difficulty: "medium",
    prompt: "A rectangle has perimeter 28 and length 8. What is its area?",
    choices: ["\\(48\\)", "\\(160\\)", "\\(56\\)", "\\(112\\)", "\\(64\\)"],
    correct: 0,
    displayAnswer: "\\(48\\)",
    explanation: "Half the perimeter is 14, so the width is \\(14 - 8 = 6\\). The area is \\(8 \\times 6 = 48\\).",
    hint: "The perimeter uses two lengths and two widths. Find the width, then multiply by the length.",
    formula: "\\[P = 2(\\ell + w),\\quad A = \\ell w\\]",
    lesson: "Perimeter and area use the side lengths differently. From the perimeter, the length plus the width equals half the perimeter. Subtract the known side, then multiply the two sides to get the area.",
    learnUrl: "https://www.mathsisfun.com/geometry/rectangle.html",
    learnLabel: "Math is Fun: Rectangles"
  },
  {
    id: "gmat-split-money",
    topic: "gmat",
    difficulty: "medium",
    prompt: "A sum of $180 is split between A and B in the ratio \\(2 : 3\\). How much does B receive?",
    choices: ["\\(\\$108\\)", "\\(\\$72\\)", "\\(\\$90\\)", "\\(\\$120\\)", "\\(\\$60\\)"],
    correct: 0,
    displayAnswer: "\\(\\$108\\)",
    explanation: "The ratio has \\(2 + 3 = 5\\) parts. B gets 3 of them: \\(\\dfrac{3}{5} \\times 180 = 108\\) dollars.",
    hint: "B corresponds to the 3 in the ratio. Divide 180 by the total number of parts, then multiply by 3.",
    formula: "\\[\\text{B's share} = \\frac{b}{a + b} \\times \\text{total}\\]",
    lesson: "A ratio split divides the total into as many equal parts as the ratio numbers add to. Each person receives their own number of those parts. The two shares add back to the original total, which is a useful check.",
    learnUrl: "https://www.mathsisfun.com/numbers/ratio.html",
    learnLabel: "Math is Fun: Ratios"
  },
  {
    id: "gmat-exp-eq",
    topic: "gmat",
    difficulty: "medium",
    prompt: "If \\(4^x = 64\\), what is \\(x\\)?",
    choices: ["\\(3\\)", "\\(4\\)", "\\(6\\)", "\\(16\\)", "\\(2\\)"],
    correct: 0,
    displayAnswer: "\\(3\\)",
    explanation: "Rewrite 64 as a power of 4: \\(4^3 = 64\\). The exponents match, so \\(x = 3\\).",
    hint: "Express 64 as 4 raised to an integer power. That exponent is x.",
    formula: "\\[a^x = a^k \\quad\\Rightarrow\\quad x = k\\quad (a > 0,\\ a \\neq 1)\\]",
    lesson: "Equal powers with the same base have equal exponents. Rewriting the right side with the left side's base makes the exponent readable. A different base, such as 2, changes the exponent even though the value is the same.",
    learnUrl: "https://www.mathsisfun.com/algebra/exponent-laws.html",
    learnLabel: "Math is Fun: Exponent Laws"
  },
  {
    id: "gmat-pool-drain",
    topic: "gmat",
    difficulty: "hard",
    prompt: "Pipe A fills a pool in 4 hours, pipe B fills it in 6 hours, and a drain empties a full pool in 12 hours. All three are opened when the pool is empty. How long does it take to fill the pool?",
    choices: ["\\(3\\) hours", "\\(2\\) hours", "\\(22\\) hours", "\\(6\\) hours", "\\(4\\) hours"],
    correct: 0,
    displayAnswer: "\\(3\\) hours",
    explanation: "The combined rate is \\(\\dfrac{1}{4} + \\dfrac{1}{6} - \\dfrac{1}{12} = \\dfrac{1}{3}\\) pool per hour. Filling one pool takes 3 hours.",
    hint: "Treat the drain as a negative rate. Add the two filling rates and subtract the draining rate.",
    formula: "\\[\\frac{1}{t} = \\frac{1}{a} + \\frac{1}{b} - \\frac{1}{d}\\]",
    lesson: "Filling contributes a positive rate and draining contributes a negative rate, each as a fraction of the pool per hour. Use a common denominator to add those fractions. The time to fill one pool is the reciprocal of the net rate, provided that net rate is positive.",
    learnUrl: "https://www.mathsisfun.com/algebra/word-questions-solving.html",
    learnLabel: "Math is Fun: Solving Word Questions"
  },
  {
    id: "gmat-salt",
    topic: "gmat",
    difficulty: "hard",
    prompt: "How many liters of a 20% salt solution must be added to 10 liters of a 50% salt solution to make a 30% salt solution?",
    choices: ["\\(20\\) liters", "\\(10\\) liters", "\\(15\\) liters", "\\(50\\) liters", "\\(30\\) liters"],
    correct: 0,
    displayAnswer: "\\(20\\) liters",
    explanation: "Let \\(x\\) be the liters of 20% solution. Then \\(0.2x + 0.5 \\cdot 10 = 0.3(x + 10)\\). Solving gives \\(0.1x = 2\\), so \\(x = 20\\).",
    hint: "Track the amount of salt, not just the volume. The salt in both starting solutions equals the salt in the mixture.",
    formula: "\\[c_1 x + c_2 v = c(x + v)\\]",
    lesson: "Mixture equations balance the amount of pure substance. Each part contributes its concentration times its volume. The final volume is the sum of the volumes, and the final concentration applies to that sum. A concentration by itself is not a volume.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "gmat-pair",
    topic: "gmat",
    difficulty: "hard",
    prompt: "The product of two positive integers is 36, and their sum is 13. What is the larger integer?",
    choices: ["\\(9\\)", "\\(6\\)", "\\(12\\)", "\\(18\\)", "\\(4\\)"],
    correct: 0,
    displayAnswer: "\\(9\\)",
    explanation: "The integers are roots of \\(t^2 - 13t + 36 = 0\\), which factors as \\((t - 4)(t - 9) = 0\\). The larger is 9.",
    hint: "Find two positive integers that multiply to 36 and add to 13. The question asks for the larger one.",
    formula: "\\[t^2 - (\\text{sum})t + (\\text{product}) = 0\\]",
    lesson: "Two numbers with a known sum and product are the roots of a quadratic whose linear coefficient is the opposite of the sum and whose constant is the product. Factoring that quadratic, or testing factor pairs of the product, finds both numbers. Report the one the question names.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "gmat-inscribed",
    topic: "gmat",
    difficulty: "hard",
    prompt: "A circle is inscribed in a square of side length 10. What is the area inside the square but outside the circle?",
    choices: ["\\(100 - 25\\pi\\)", "\\(100 - 10\\pi\\)", "\\(100 - 100\\pi\\)", "\\(25\\pi\\)", "\\(100 - 5\\pi\\)"],
    correct: 0,
    displayAnswer: "\\(100 - 25\\pi\\)",
    explanation: "The square has area \\(10^2 = 100\\). The inscribed circle has diameter 10, so its radius is 5 and its area is \\(25\\pi\\). The difference is \\(100 - 25\\pi\\).",
    hint: "Subtract the circle's area from the square's area. The circle's diameter equals the side of the square.",
    formula: "\\[A = s^2 - \\pi r^2,\\quad r = \\frac{s}{2}\\]",
    lesson: "An inscribed circle touches all four sides of the square, so its diameter is the side length and its radius is half of that. The requested region is the square minus the circle. Leaving \\(\\pi\\) in the answer keeps the area exact.",
    learnUrl: "https://www.mathsisfun.com/geometry/circle-area.html",
    learnLabel: "Math is Fun: Area of a Circle"
  },
  {
    id: "gmat-dice",
    topic: "gmat",
    difficulty: "hard",
    prompt: "Two fair six-sided dice are rolled. What is the probability that the numbers shown sum to 7?",
    choices: ["\\(\\dfrac{1}{6}\\)", "\\(\\dfrac{1}{12}\\)", "\\(\\dfrac{7}{36}\\)", "\\(\\dfrac{1}{36}\\)", "\\(\\dfrac{5}{36}\\)"],
    correct: 0,
    displayAnswer: "\\(\\dfrac{1}{6}\\)",
    explanation: "There are \\(6 \\times 6 = 36\\) equally likely outcomes, and 6 of them sum to 7: (1, 6), (2, 5), (3, 4), (4, 3), (5, 2), and (6, 1). The probability is \\(\\dfrac{6}{36} = \\dfrac{1}{6}\\).",
    hint: "Count the outcomes that add to 7, then divide by the 36 possible rolls.",
    formula: "\\[P(\\text{sum}) = \\frac{\\text{number of favorable pairs}}{36}\\]",
    lesson: "Two dice give 36 ordered outcomes, and order matters: (1, 6) and (6, 1) are different. List the pairs that hit the target sum rather than assuming the sum itself is the count. Simplify the resulting fraction.",
    learnUrl: "https://www.mathsisfun.com/data/probability.html",
    learnLabel: "Math is Fun: Probability"
  },
  {
    id: "gmat-two-changes",
    topic: "gmat",
    difficulty: "hard",
    prompt: "A price increases by 20% and then decreases by 20%. The final price is what percent of the original price?",
    choices: ["\\(96\\%\\)", "\\(100\\%\\)", "\\(80\\%\\)", "\\(64\\%\\)", "\\(104\\%\\)"],
    correct: 0,
    displayAnswer: "\\(96\\%\\)",
    explanation: "The multipliers are \\(1.20\\) and \\(0.80\\). Their product is \\(0.96\\), so the final price is 96% of the original.",
    hint: "Convert each percent change to a multiplier and multiply those factors. The two 20% changes do not cancel.",
    formula: "\\[\\text{final} = \\text{original} \\times (1 + r) \\times (1 - r)\\]",
    lesson: "Successive percent changes multiply. An increase and a later decrease of the same percent do not return to the start, because the decrease applies to the already changed price. The product \\((1 + r)(1 - r)\\) equals \\(1 - r^2\\), which is a little under 1.",
    learnUrl: "https://www.mathsisfun.com/percentage.html",
    learnLabel: "Math is Fun: Introduction to Percentages"
  },
  {
    id: "gmat-round-trip",
    topic: "gmat",
    difficulty: "hard",
    prompt: "A cyclist rides 30 miles to town at 15 miles per hour and returns along the same route at 10 miles per hour. What is the average speed for the whole trip, in miles per hour?",
    choices: ["\\(12\\)", "\\(12.5\\)", "\\(25\\)", "\\(15\\)", "\\(10\\)"],
    correct: 0,
    displayAnswer: "\\(12\\)",
    explanation: "The ride to town takes \\(30 / 15 = 2\\) hours and the return takes \\(30 / 10 = 3\\) hours. The average speed is \\(60 / 5 = 12\\) miles per hour.",
    hint: "Average speed is total distance divided by total time. The two legs take different amounts of time.",
    formula: "\\[\\text{average speed} = \\frac{2d}{\\dfrac{d}{r_1} + \\dfrac{d}{r_2}} = \\frac{2 r_1 r_2}{r_1 + r_2}\\]",
    lesson: "Average speed on a trip is total distance over total time. When the legs have equal length but different speeds, more time is spent on the slower leg, so the average is the harmonic mean of the two speeds, not their arithmetic mean.",
    learnUrl: "https://www.mathsisfun.com/measure/speed-velocity.html",
    learnLabel: "Math is Fun: Speed and Velocity"
  },
  {
    id: "gmat-must-divide",
    topic: "gmat",
    difficulty: "hard",
    prompt: "If \\(n\\) is an integer and \\(3n\\) is divisible by 12, which of the following must be true?",
    choices: ["\\(n\\) is divisible by 4", "\\(n\\) is divisible by 12", "\\(n\\) is divisible by 6", "\\(n\\) is odd", "\\(n\\) is divisible by 8"],
    correct: 0,
    displayAnswer: "\\(n\\) is divisible by 4",
    explanation: "\\(3n = 12k\\) means \\(n = 4k\\), so 4 divides \\(n\\). The case \\(n = 4\\) satisfies the hypothesis, and 4 is not odd and is not divisible by 6, 8, or 12.",
    hint: "Divide both sides of the divisibility relationship by the factor that 3 and 12 share. Then test a single value that still works.",
    formula: "\\[\\text{If } 3n = 12k, \\text{ then } n = 4k.\\]",
    lesson: "A 'must be true' statement has to hold for every integer that meets the hypothesis. Solving the equation shows the strongest condition that always follows. One counterexample is enough to reject each of the other statements.",
    learnUrl: "https://www.mathsisfun.com/definitions/divisible.html",
    learnLabel: "Math is Fun: Divisible"
  },
  {
    id: "gmat-ds-linear",
    topic: "gmat",
    difficulty: "easy",
    shuffle: false,
    prompt: "Data sufficiency. What is the value of \\(x\\)?\n(1) \\(x + 3 = 10\\)\n(2) \\(x > 0\\)",
    choices: [
      "Statement (1) alone is sufficient, but statement (2) alone is not.",
      "Statement (2) alone is sufficient, but statement (1) alone is not.",
      "Both statements together are sufficient, but neither statement alone is.",
      "Each statement alone is sufficient.",
      "The statements together are not sufficient."
    ],
    correct: 0,
    displayAnswer: "Statement (1) alone is sufficient, but statement (2) alone is not.",
    explanation: "Statement (1) gives \\(x = 7\\), which is one value. Statement (2) only says \\(x\\) is positive, so it leaves many values. Statement (1) is enough on its own.",
    hint: "A statement is sufficient when it produces exactly one value of x. Test each statement by itself before you combine them.",
    formula: "\\[x + b = c \\quad\\Rightarrow\\quad x = c - b\\]",
    lesson: "Data sufficiency asks whether the given facts determine the answer, not merely what the answer is. An equation that isolates one value is sufficient. An inequality that leaves an interval is not, even if the equation's value happens to lie in that interval.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Equations"
  },
  {
    id: "gmat-ds-sign",
    topic: "gmat",
    difficulty: "medium",
    shuffle: false,
    prompt: "Data sufficiency. Is \\(x > 0\\)?\n(1) \\(x > -2\\)\n(2) \\(x < 3\\)",
    choices: [
      "Statement (1) alone is sufficient, but statement (2) alone is not.",
      "Statement (2) alone is sufficient, but statement (1) alone is not.",
      "Both statements together are sufficient, but neither statement alone is.",
      "Each statement alone is sufficient.",
      "The statements together are not sufficient."
    ],
    correct: 4,
    displayAnswer: "The statements together are not sufficient.",
    explanation: "Statement (1) allows both \\(x = -1\\) and \\(x = 1\\). Statement (2) does too. Together they only give \\(-2 < x < 3\\), which still includes both signs, so the facts are not sufficient.",
    hint: "For a yes-or-no question, the statements are sufficient only when they force one answer. Try one positive value and one negative value.",
    formula: "\\[\\text{A yes-or-no question needs the facts to force a single answer.}\\]",
    lesson: "Narrowing a variable to an interval is not enough when that interval still contains both a yes and a no. Check each statement alone, then check them together. If a yes and a no both survive the combined facts, the statements are not sufficient.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearInequalities.aspx",
    learnLabel: "Paul's Online Math Notes: Linear Inequalities"
  },
  {
    id: "gmat-ds-sum",
    topic: "gmat",
    difficulty: "medium",
    shuffle: false,
    prompt: "Data sufficiency. What is the value of \\(x + y\\)?\n(1) \\(x = 4\\)\n(2) \\(y = 6\\)",
    choices: [
      "Statement (1) alone is sufficient, but statement (2) alone is not.",
      "Statement (2) alone is sufficient, but statement (1) alone is not.",
      "Both statements together are sufficient, but neither statement alone is.",
      "Each statement alone is sufficient.",
      "The statements together are not sufficient."
    ],
    correct: 2,
    displayAnswer: "Both statements together are sufficient, but neither statement alone is.",
    explanation: "Statement (1) fixes \\(x\\) but not \\(y\\), and statement (2) fixes \\(y\\) but not \\(x\\). Together, \\(x + y = 4 + 6 = 10\\).",
    hint: "The question asks for the sum. See whether each statement alone determines both pieces of that sum.",
    formula: "\\[x + y = s\\]",
    lesson: "A sum is determined only when every unknown in it is determined, or when the statements give the sum directly. One variable's value leaves the sum free. Using both statements is the right conclusion when each one fails alone and the pair succeeds.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx",
    learnLabel: "Paul's Online Math Notes: Systems of Equations"
  },
  {
    id: "gmat-ds-square",
    topic: "gmat",
    difficulty: "hard",
    shuffle: false,
    prompt: "Data sufficiency. Is \\(x^2 > x\\)?\n(1) \\(x > 1\\)\n(2) \\(x < 0\\)",
    choices: [
      "Statement (1) alone is sufficient, but statement (2) alone is not.",
      "Statement (2) alone is sufficient, but statement (1) alone is not.",
      "Both statements together are sufficient, but neither statement alone is.",
      "Each statement alone is sufficient.",
      "The statements together are not sufficient."
    ],
    correct: 3,
    displayAnswer: "Each statement alone is sufficient.",
    explanation: "\\(x^2 > x\\) is the same as \\(x(x - 1) > 0\\), which holds for every \\(x > 1\\) and every \\(x < 0\\). Each statement forces a yes, so each is sufficient alone.",
    hint: "Rearrange the inequality to x(x - 1) > 0 and see where that product is positive. Then see whether each statement sits entirely inside one of those regions.",
    formula: "\\[x^2 - x > 0 \\quad\\Leftrightarrow\\quad x(x - 1) > 0\\]",
    lesson: "A yes-or-no statement is sufficient when every value it allows gives the same answer. The inequality \\(x^2 > x\\) is true on two separate rays. A statement that lands entirely on one of those rays answers yes, even if the other statement lands on the other ray.",
    learnUrl: "https://tutorial.math.lamar.edu/Classes/Alg/SolveQuadraticEqnsI.aspx",
    learnLabel: "Paul's Online Math Notes: Quadratic Equations"
  },
  {
    id: "gmat-ds-multiple",
    topic: "gmat",
    difficulty: "hard",
    shuffle: false,
    prompt: "Data sufficiency. \\(n\\) is an integer greater than 10 and less than 20. What is the value of \\(n\\)?\n(1) \\(n\\) is a multiple of 3.\n(2) \\(n\\) is a multiple of 5.",
    choices: [
      "Statement (1) alone is sufficient, but statement (2) alone is not.",
      "Statement (2) alone is sufficient, but statement (1) alone is not.",
      "Both statements together are sufficient, but neither statement alone is.",
      "Each statement alone is sufficient.",
      "The statements together are not sufficient."
    ],
    correct: 1,
    displayAnswer: "Statement (2) alone is sufficient, but statement (1) alone is not.",
    explanation: "The integers from 11 through 19 that are multiples of 3 are 12, 15, and 18, so statement (1) is not enough. The only multiple of 5 in that range is 15, so statement (2) is enough alone.",
    hint: "List the integers strictly between 10 and 20 before you apply each statement. Sufficient means exactly one possible n.",
    formula: "\\[10 < n < 20,\\quad n \\in \\mathbb{Z}\\]",
    lesson: "A value question is sufficient only when one number remains. Listing the integers in an open range avoids accidentally including the endpoints. One statement can be enough even when the other statement leaves several possibilities.",
    learnUrl: "https://www.mathsisfun.com/numbers/factors-multiples.html",
    learnLabel: "Math is Fun: Factors and Multiples"
  }
];
